export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            background: "#45A888",
            padding: "10px",
            fontSize: "24px",
          }}
        >
          <h1>Header</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
